<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>..\..\Build\Bots</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>..\..\Build\Bots</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\Source\NasdaqTrader.Bot.Core\NasdaqTrader.Bot.Core.csproj" />
      <ProjectReference Include="..\..\Source\NasdaqTrader.CLI\NasdaqTrader.CLI.csproj" />
      <ProjectReference Include="..\..\Source\NasdaqTraderSystem.Core\NasdaqTraderSystem.Core.csproj" />
      <ProjectReference Include="..\..\Source\NasdaqTraderSystem.Html\NasdaqTraderSystem.Html.csproj" />
    </ItemGroup>

</Project>
